### ISSUE TITLE
Error while trying to read env.yml outside the root path

### ISSUE THREAD

**Issue by martinhummer** [helhum/TYPO3-Distribution#10]
On my webhost, there is a basedir restriction to my web path.
YamlFileReader.php tries to read a file in ../../../shared/Configuration/env.yml
If this path is not allowed to access, the following error occurs in the backend:

<img width="1783" alt="bildschirmfoto 2017-10-12 um 08 49 25" src="https://user-images.githubusercontent.com/2011467/31482919-954509d6-af2a-11e7-8da9-58e3c08d0c3b.png">

**Comment by helhum** [comment]
Thanks for your report.

> On my webhost, there is a basedir restriction to my web path

The only solution here is to allow this path in the webserver/ php configuration or to remove this line from the configuration in your project and only include files that are within your open basedir paths

**Comment by martinhummer** [comment]
Thanks for your reply Helmut!

I reported this because I thought there maybe a possibility to catch this error.
But of course I can remove the line from conf/config.yml

Great Distribution by the way, really inspiring!

**Comment by helhum** [comment]
> I reported this because I thought there maybe a possibility to catch this error.

There is, however the only option would be to change `file_exists` to `@file_exists`, which would
mute the error/exception, but would make finding the error a real pain, in case someone relies on such config file to be included.

> Great Distribution by the way, really inspiring!

Good to hear, thanks!
