### ISSUE TITLE
Error Message while parsing dev.config.yml

### ISSUE THREAD

**Issue by martinhummer** [helhum/TYPO3-Distribution#14]
During installation i get the attached Error Message.
<img width="1955" alt="bildschirmfoto 2018-02-07 um 11 49 16" src="https://user-images.githubusercontent.com/2011467/35912554-32b8afb8-0bfd-11e8-98da-c14260596ef6.png">

My solution is quoting line 25 in dev.config.yml
`transport_mbox_file: '%env(TYPO3_PATH_COMPOSER_ROOT)%/var/log/sent-mails.log'`

**Comment by helhum** [comment]
Thanks fixed this now. I would nevertheless be interested in what version of `symfony/yaml` you were using when getting this error message (as I didn't get this before)

**Comment by martinhummer** [comment]
Thanks Helmut, it is working now!
I'm using version 4.0.4 of symfony/yaml
<img width="406" alt="bildschirmfoto 2018-02-15 um 09 43 41" src="https://user-images.githubusercontent.com/2011467/36247985-359e3588-1236-11e8-8ec5-015bcdf14bd0.png">

One last request:
At the moment I can not install the newest version including your fix via composer.
Maybe due to a not updated version on packagist?

**Comment by helhum** [comment]
> I'm using version 4.0.4 of symfony/yaml

ah, ok. version 4 seems to be more restrictive here

> Maybe due to a not updated version on packagist

I tagged 8.2.1 for your convenience :)

**Comment by martinhummer** [comment]
Great, thank you!
