### ISSUE TITLE
.env variables not fetched

### ISSUE THREAD

**Issue by stat1x** [helhum/TYPO3-Distribution#15]
When I do `composer install --no-dev` my .env variables set in .env file are not fetched. The generated `AdditionalConfiguration.php` file contains only the default values.

For example I have defined .env variables for the DB connection like this : 
```
TYPO3_INSTALL_DB_DBNAME='typo3_dbname'
TYPO3_INSTALL_DB_HOST='localhost'
TYPO3_INSTALL_DB_PASSWORD='password'
TYPO3_INSTALL_DB_USER='root'
```
And in the `AdditionalConfiguration.php` I get this after `composer install --no-dev` : 
```
// Auto generated by helhum/typo3-config-handling
// Do not edit this file
$GLOBALS['TYPO3_CONF_VARS'] = [
...
'DB' => [
        'Connections' => [
            'Default' => [
                'charset' => 'utf8',
                'dbname' => false,
                'driver' => 'mysqli',
                'host' => false,
                'password' => false,
                'port' => '',
                'unix_socket' => '',
                'user' => false,
            ],
        ],
    ],
...
];
```
If I do not use the `--no-dev` flag I have :
```
// Auto generated by helhum/typo3-config-handling
// Do not edit this file
(new \Helhum\TYPO3\ConfigHandling\ConfigLoader(
    \Helhum\TYPO3\ConfigHandling\RootConfig::getRootConfigFile()
))->populate();
```
Did I miss something?

Thanks,
Jérémie

**Comment by helhum** [comment]
> When I do composer install --no-dev my .env variables set in .env file are not fetched

Yes, this is correct, because the `helhum/dotenv-connector` connector package in my distribution is only a [dev-dependency](https://github.com/helhum/TYPO3-Distribution/blob/cc5a8d5579e4a6ee77693e7070fb36704726e63f/composer.json#L33-L34)

You need to either populate the environment variables or have `helhum/dotenv-connector` as non dev dependency.
