### ISSUE TITLE
Deploy via TYPO3 Surf- package typo3_console not found

### ISSUE THREAD

**Issue by codemonkey1988** [helhum/TYPO3-Distribution#2]
I am currently trying out your TYPO3 Distribution, because I think it's great. While trying to deploy the test project with TYPO3 Surf and your example configuration, I noticed a problem with that.

TYPO3 Surf cannot find your typo3_console package, because it only looks at the path typo3conf/ext/typo3_console for it. But the typo3_console package is located in vendor/helhum/typo3-console.

I am using the master branch of your TYPO3 Distribution with TYPO3 Surf 2.0.0-beta6.

As a workaround, I created my own tasks to flush cashes and generate the PackagesStates.php.

**Comment by helhum** [comment]
Yeah, that's unfortunately true. I try to get this resolved in Surf during the weekend.

**Comment by simonschaufi** [comment]
This has been fixed already and can be closed.

**Comment by helhum** [comment]
fixed in console
